version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: ko-postgres
    restart: always
    environment:
      POSTGRES_USER: kouser
      POSTGRES_PASSWORD: 200125
      POSTGRES_DB: ko_user
    ports:
      - "5432:5432"
    volumes:
      - ko_postgres_data:/var/lib/postgresql/data

volumes:
  ko_postgres_data: