spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ko_user
    driver-class-name: org.postgresql.Driver
    username: kouser
    password: 200125
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081


jwt:
  secret: k8d9F@1xQmPz!93LxW0sA9d#2pVb7nXc
kind: Application